#!/usr/bin/env node
/* Capacitor's webDir must be ONE directory that becomes the native app's
   bundled web root. This repo's production layout is three siblings
   (site/, admin/, shared/) served from one Caddy root -- admin/ already
   imports shared/ via relative paths like '../../../shared/dom.js' that
   assume that exact sibling layout, and nothing about those paths should
   change just because a native wrapper exists now too.

   So rather than repoint webDir at the repo root (which would also bundle
   the public marketing site into a field-tech's app for no reason) or
   rewrite every admin import path, this copies just admin/ + shared/ into
   mobile/www/ -- a disposable staging copy, regenerated by this script
   before every `cap sync`/`cap copy`, and gitignored. admin/ and shared/
   stay the single source of truth; nothing here is ever hand-edited. */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const WWW = path.join(ROOT, 'mobile', 'www');

function copyDir(src, dest) {
  fs.rmSync(dest, { recursive: true, force: true });
  fs.cpSync(src, dest, { recursive: true });
}

copyDir(path.join(ROOT, 'admin'), path.join(WWW, 'admin'));
copyDir(path.join(ROOT, 'shared'), path.join(WWW, 'shared'));

// The native app's actual screen is admin/field.html, not a root index.html
// -- Capacitor expects an index.html at webDir's root as the load target,
// so this is a one-line redirect rather than a second copy of field.html
// (which would be exactly the duplicated-source-of-truth problem this
// whole script exists to avoid).
fs.writeFileSync(path.join(WWW, 'index.html'),
  '<!doctype html><html><head><meta charset="utf-8">' +
  '<meta http-equiv="refresh" content="0;url=admin/field.html">' +
  '<script>location.replace("admin/field.html");</script></head>' +
  '<body>Loading Nova Shield Field…</body></html>\n');

console.log(`Synced admin/ + shared/ -> ${path.relative(ROOT, WWW)}/`);
